language: python
python:
- 3.7
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.9
    - verilator
    - libgmp-dev
    - libmpfr-dev
    - libmpc-dev
    - verilator

before_install:
- mkdir deps
- mkdir deps/bin
- mkdir deps/lib
- mkdir deps/include
# install conda
- wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
- chmod +x miniconda.sh
- ./miniconda.sh -b -p $TRAVIS_BUILD_DIR/miniconda
- export PATH=$TRAVIS_BUILD_DIR/miniconda/bin:$PATH
- hash -r
- conda config --set always_yes yes --set changeps1 no
- conda update -q conda
- conda create -q -n test-env python=3.7
- source activate test-env
- conda install pip
install:
# install coreir
- curl -s -L https://github.com/rdaly525/coreir/releases/latest | grep "href.*coreir-${TRAVIS_OS_NAME}.tar.gz" | cut -d \" -f 2 | xargs -I {} wget https://github.com"{}"
- mkdir coreir_release;
- tar -xf coreir-${TRAVIS_OS_NAME}.tar.gz -C coreir_release --strip-components 1;
- cd coreir_release && sudo make install && cd ..

- pip install pysmt
- pysmt-install --z3 --confirm-agreement
- export PYTHONPATH="/home/travis/.smt_solvers/python-bindings-3.6:${PYTHONPATH}"
- export LD_LIBRARY_PATH="/home/travis/.smt_solvers/python-bindings-3.6:${LD_LIBRARY_PATH}"
- pysmt-install --check
- pip install pytest-cov
- git clone https://github.com/phanrahan/peak.git
  #- git clone https://github.com/leonardt/pycoreir.git
- pip install git+git://github.com/leonardt/Pyverilog.git#egg=pyverilog
  #- pip install coreir
#- pip install git+git://github.com/phanrahan/magma#egg=magma
#- pip install git+git://github.com/phanrahan/mantle#egg=mantle
- pip install -e ./peak
  #- pip install D-e ./pycoreir
- pip install -e .
- pip install hwtypes
script:
- pytest tests/
